### ISSUE TITLE
getSafeTestName() should make the test names more specific

### ISSUE THREAD

**Issue by advancedcbyrne** [uchagani/junit-playwright#35]
While running tests in Jenkins, I noticed that Playwright trace file names only had the test method name in the file name (eg, MyTest.zip).  If there are tests with the same name but different parameters, just using the test method name may not be specific enough and previous zip files may be overwritten.  Threading may need to be taken in to account as well but not sure.

It is possible the following method needs to be changed:  https://github.com/uchagani/junit-playwright/blob/develop/src/main/java/io/github/uchagani/jp/PlaywrightTestWatcher.java#L55-L57

**Comment by uchagani** [comment]
Thanks for reporting this.  Should be fixed in v3.0.1.  Please try that version and if it doesn't work report back.

**Comment by uchagani** [comment]
@advancedcbyrne my bad, the latest version will NOT work for parameteriezed tests (and might even crash).  I would recommend not upgrading just yet.  I'll reopen this and push up a new release when it's fixed.

**Comment by uchagani** [comment]
Fixed via #42 .  @advancedcbyrne you can now junit 5's `@DisplayName` annotation as the trace file name or if using `@ParameterizedTest` annotation, you can use the `name` option and that is what will be used for the trace file name.
