### ISSUE TITLE
Hooks classes

### ISSUE THREAD

**Issue by km9134** [uchagani/junit-playwright#43]
Is there away to add cookie accepts etc in the hooks class before running the test? 

If we are injecting the context into the test how do we interact with that context outside of the test?

**Comment by uchagani** [comment]
Hi, you can just inject it into the hook:

```java
@BeforeEach 
public void beforeEach(BrowserContext context) {
  // do something with the context 
}
```

**Comment by km9134** [comment]
Hi,

Thanks for that, if I inject the context then into a test it's the same context? It'll have those cookies accepted?

Very cool code you've written allows for concurrent parallelism without lots of synchronisation and thread safety.

Would love to understand more about how you did it!

**Comment by uchagani** [comment]
Yup same one. And if it's not, it's a bug so if you find that is the case please let me know.

**Comment by uchagani** [comment]
> Would love to understand more about how you did it!

Feel free to ask any questions about the code.

I built class-level parallel tests directly into playwright-java (should be out soon). But I will keep this library going until method-level parallel is achieved in playwright-java directly.

**Comment by km9134** [comment]
I'll come back to you when I go through the code some more!

I did try method level parallel testing with JUnit and playwright but I couldn't get the thread safety to work.Seemed to still conflict even when I added instance per method. Be cool to see it in playwright natively be advantage over sequential testing!

You library solves this though!
